"""Create follow table

Revision ID: 1aef43a6bee5
Revises: f7fa98555c7b
Create Date: 2025-07-11 15:31:56.114337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aef43a6bee5'
down_revision: Union[str, Sequence[str], None] = 'f7fa98555c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('who', sa.Integer(), nullable=False),
    sa.Column('whom', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['who'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whom'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    # ### end Alembic commands ###
