"""StoryViews table

Revision ID: 1e9e9fc5025b
Revises: a15018b2c66f
Create Date: 2025-07-17 23:59:04.906728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9e9fc5025b'
down_revision: Union[str, Sequence[str], None] = 'a15018b2c66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'story_views',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('story_id', sa.Integer(), sa.ForeignKey('stories.id', ondelete='CASCADE'), nullable=False),
        sa.Column('viewer_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('viewed_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.UniqueConstraint('story_id', 'viewer_id', name='unique_story_views')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_views')
    # ### end Alembic commands ###
