"""In users table profile_image->profile_image_url

Revision ID: 2a9f4b122702
Revises: 1aef43a6bee5
Create Date: 2025-07-13 10:10:59.184935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9f4b122702'
down_revision: Union[str, Sequence[str], None] = '1aef43a6bee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.String(), server_default='default_profile.png', nullable=False))
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.VARCHAR(), server_default=sa.text("'default_profile.png'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('users', 'profile_image_url')
    # ### end Alembic commands ###
