"""storyviews table

Revision ID: 8194fe809415
Revises: a15018b2c66f
Create Date: 2025-07-18 11:22:14.600805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8194fe809415'
down_revision: Union[str, Sequence[str], None] = 'a15018b2c66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'story_views',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('story_id', sa.Integer(), nullable=False),
        sa.Column('viewer_id', sa.Integer(), nullable=False),
        sa.Column('viewed_at', sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),

        sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='CASCADE'),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_views')
    # ### end Alembic commands ###
