"""Create save posts table

Revision ID: a8fad193b0af
Revises: caccf70f6f4f
Create Date: 2025-07-10 12:30:26.835499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8fad193b0af'
down_revision: Union[str, Sequence[str], None] = 'caccf70f6f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saveposts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uix_user_post')
    )
    op.add_column('posts', sa.Column('image_url', sa.String(), nullable=False))
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'image_url')
    op.drop_table('saveposts')
    # ### end Alembic commands ###
